name: Publish

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      - run: deno install
      - run: deno task test
      - run: deno fmt --check
      # - run: deno lint

  publish-jsr:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      - run: deno publish --allow-slow-types
